.phony : inc
.phony : buildInstall
.phony : install
.phony : clean

inc :;

install : buildInstall
	echo "util libs installed"

buildInstall : ;
	-rm ../*.h
	@$(MAKE) -f ../makefile.$(HOST_ARCH)
	mkdir -p ../../../../lib/$(HOST_ARCH)
	cp libEdmUtil.a ../../../../lib/$(HOST_ARCH)
	cp libEdmUtil.so ../../../../lib/$(HOST_ARCH)
