#!/bin/sh
EDMOBJECTS=$(EDM_CONFIGS)
EDMPVOBJECTS=$(EDM_CONFIGS)
EDMFILES=$(EDM_CONFIGS)
EDMLIBS=$(EDM_LIBS)
EDMHELPFILES=$(EDM_HELP)
EPICS_CA_MAX_ARRAY_BYTES=$($=$){EPICS_CA_MAX_ARRAY_BYTES:=1000000}
export EPICS_CA_MAX_ARRAY_BYTES EDMOBJECTS EDMPVOBJECTS EDMFILES EDMHELPFILES EDMLIBS
XMODIFIERS= $(EDM_INSTALL)/edmMain $*
